version: '2.0'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=lunafoodUser
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=lunafood
    ports:
      - 5433:5432
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
      image: wurstmeister/kafka
      ports:
        - "9092:9092"
      environment:
        LOG_DIR: "/tmp/logs"
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - zookeeper